version: '3'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /usr/src/app
    volumes:
      - ./Backend:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./Frontend:/usr/src/app
    ports:
      - "3001:3001"
    command: npm start
